/* This file was generated by SableCC (http://www.sablecc.org/). */

package cordel.node;

import cordel.analysis.*;

@SuppressWarnings("nls")
public final class ABoolSimVariavel extends PVariavel
{
    private TBoolSim _boolSim_;

    public ABoolSimVariavel()
    {
        // Constructor
    }

    public ABoolSimVariavel(
        @SuppressWarnings("hiding") TBoolSim _boolSim_)
    {
        // Constructor
        setBoolSim(_boolSim_);

    }

    @Override
    public Object clone()
    {
        return new ABoolSimVariavel(
            cloneNode(this._boolSim_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABoolSimVariavel(this);
    }

    public TBoolSim getBoolSim()
    {
        return this._boolSim_;
    }

    public void setBoolSim(TBoolSim node)
    {
        if(this._boolSim_ != null)
        {
            this._boolSim_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._boolSim_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._boolSim_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._boolSim_ == child)
        {
            this._boolSim_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._boolSim_ == oldChild)
        {
            setBoolSim((TBoolSim) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
