/* This file was generated by SableCC (http://www.sablecc.org/). */

package cordel.node;

import cordel.analysis.*;

@SuppressWarnings("nls")
public final class AExpPrioridadeTerm extends PTerm
{
    private TEPar _ePar_;
    private PExp _exp_;
    private TDPar _dPar_;

    public AExpPrioridadeTerm()
    {
        // Constructor
    }

    public AExpPrioridadeTerm(
        @SuppressWarnings("hiding") TEPar _ePar_,
        @SuppressWarnings("hiding") PExp _exp_,
        @SuppressWarnings("hiding") TDPar _dPar_)
    {
        // Constructor
        setEPar(_ePar_);

        setExp(_exp_);

        setDPar(_dPar_);

    }

    @Override
    public Object clone()
    {
        return new AExpPrioridadeTerm(
            cloneNode(this._ePar_),
            cloneNode(this._exp_),
            cloneNode(this._dPar_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExpPrioridadeTerm(this);
    }

    public TEPar getEPar()
    {
        return this._ePar_;
    }

    public void setEPar(TEPar node)
    {
        if(this._ePar_ != null)
        {
            this._ePar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ePar_ = node;
    }

    public PExp getExp()
    {
        return this._exp_;
    }

    public void setExp(PExp node)
    {
        if(this._exp_ != null)
        {
            this._exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp_ = node;
    }

    public TDPar getDPar()
    {
        return this._dPar_;
    }

    public void setDPar(TDPar node)
    {
        if(this._dPar_ != null)
        {
            this._dPar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._dPar_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._ePar_)
            + toString(this._exp_)
            + toString(this._dPar_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._ePar_ == child)
        {
            this._ePar_ = null;
            return;
        }

        if(this._exp_ == child)
        {
            this._exp_ = null;
            return;
        }

        if(this._dPar_ == child)
        {
            this._dPar_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._ePar_ == oldChild)
        {
            setEPar((TEPar) newChild);
            return;
        }

        if(this._exp_ == oldChild)
        {
            setExp((PExp) newChild);
            return;
        }

        if(this._dPar_ == oldChild)
        {
            setDPar((TDPar) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
