/* This file was generated by SableCC (http://www.sablecc.org/). */

package cordel.node;

import cordel.analysis.*;

@SuppressWarnings("nls")
public final class AListaExp extends PListaExp
{
    private PListaAux1 _listaAux1_;

    public AListaExp()
    {
        // Constructor
    }

    public AListaExp(
        @SuppressWarnings("hiding") PListaAux1 _listaAux1_)
    {
        // Constructor
        setListaAux1(_listaAux1_);

    }

    @Override
    public Object clone()
    {
        return new AListaExp(
            cloneNode(this._listaAux1_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAListaExp(this);
    }

    public PListaAux1 getListaAux1()
    {
        return this._listaAux1_;
    }

    public void setListaAux1(PListaAux1 node)
    {
        if(this._listaAux1_ != null)
        {
            this._listaAux1_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._listaAux1_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._listaAux1_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._listaAux1_ == child)
        {
            this._listaAux1_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._listaAux1_ == oldChild)
        {
            setListaAux1((PListaAux1) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
