/* This file was generated by SableCC (http://www.sablecc.org/). */

package cordel.node;

import java.util.*;
import cordel.analysis.*;

@SuppressWarnings("nls")
public final class AParametrosAux1 extends PParametrosAux1
{
    private PParametro _parametro_;
    private final LinkedList<PParametrosAux2> _parametrosAux2_ = new LinkedList<PParametrosAux2>();

    public AParametrosAux1()
    {
        // Constructor
    }

    public AParametrosAux1(
        @SuppressWarnings("hiding") PParametro _parametro_,
        @SuppressWarnings("hiding") List<?> _parametrosAux2_)
    {
        // Constructor
        setParametro(_parametro_);

        setParametrosAux2(_parametrosAux2_);

    }

    @Override
    public Object clone()
    {
        return new AParametrosAux1(
            cloneNode(this._parametro_),
            cloneList(this._parametrosAux2_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAParametrosAux1(this);
    }

    public PParametro getParametro()
    {
        return this._parametro_;
    }

    public void setParametro(PParametro node)
    {
        if(this._parametro_ != null)
        {
            this._parametro_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parametro_ = node;
    }

    public LinkedList<PParametrosAux2> getParametrosAux2()
    {
        return this._parametrosAux2_;
    }

    public void setParametrosAux2(List<?> list)
    {
        for(PParametrosAux2 e : this._parametrosAux2_)
        {
            e.parent(null);
        }
        this._parametrosAux2_.clear();

        for(Object obj_e : list)
        {
            PParametrosAux2 e = (PParametrosAux2) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._parametrosAux2_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._parametro_)
            + toString(this._parametrosAux2_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._parametro_ == child)
        {
            this._parametro_ = null;
            return;
        }

        if(this._parametrosAux2_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._parametro_ == oldChild)
        {
            setParametro((PParametro) newChild);
            return;
        }

        for(ListIterator<PParametrosAux2> i = this._parametrosAux2_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PParametrosAux2) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
