/* This file was generated by SableCC (http://www.sablecc.org/). */

package cordel.node;

import cordel.analysis.*;

@SuppressWarnings("nls")
public final class AParametrosAux2 extends PParametrosAux2
{
    private TEParametro _eParametro_;
    private PParametro _parametro_;

    public AParametrosAux2()
    {
        // Constructor
    }

    public AParametrosAux2(
        @SuppressWarnings("hiding") TEParametro _eParametro_,
        @SuppressWarnings("hiding") PParametro _parametro_)
    {
        // Constructor
        setEParametro(_eParametro_);

        setParametro(_parametro_);

    }

    @Override
    public Object clone()
    {
        return new AParametrosAux2(
            cloneNode(this._eParametro_),
            cloneNode(this._parametro_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAParametrosAux2(this);
    }

    public TEParametro getEParametro()
    {
        return this._eParametro_;
    }

    public void setEParametro(TEParametro node)
    {
        if(this._eParametro_ != null)
        {
            this._eParametro_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._eParametro_ = node;
    }

    public PParametro getParametro()
    {
        return this._parametro_;
    }

    public void setParametro(PParametro node)
    {
        if(this._parametro_ != null)
        {
            this._parametro_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parametro_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._eParametro_)
            + toString(this._parametro_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._eParametro_ == child)
        {
            this._eParametro_ = null;
            return;
        }

        if(this._parametro_ == child)
        {
            this._parametro_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._eParametro_ == oldChild)
        {
            setEParametro((TEParametro) newChild);
            return;
        }

        if(this._parametro_ == oldChild)
        {
            setParametro((PParametro) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
