/* This file was generated by SableCC (http://www.sablecc.org/). */

package cordel.node;

import cordel.analysis.*;

@SuppressWarnings("nls")
public final class AParametros extends PParametros
{
    private PParametrosAux1 _parametrosAux1_;

    public AParametros()
    {
        // Constructor
    }

    public AParametros(
        @SuppressWarnings("hiding") PParametrosAux1 _parametrosAux1_)
    {
        // Constructor
        setParametrosAux1(_parametrosAux1_);

    }

    @Override
    public Object clone()
    {
        return new AParametros(
            cloneNode(this._parametrosAux1_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAParametros(this);
    }

    public PParametrosAux1 getParametrosAux1()
    {
        return this._parametrosAux1_;
    }

    public void setParametrosAux1(PParametrosAux1 node)
    {
        if(this._parametrosAux1_ != null)
        {
            this._parametrosAux1_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parametrosAux1_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._parametrosAux1_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._parametrosAux1_ == child)
        {
            this._parametrosAux1_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._parametrosAux1_ == oldChild)
        {
            setParametrosAux1((PParametrosAux1) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
