/* This file was generated by SableCC (http://www.sablecc.org/). */

package cordel.node;

import cordel.analysis.*;

@SuppressWarnings("nls")
public final class AStringVariavel extends PVariavel
{
    private TCaractereVetor _caractereVetor_;

    public AStringVariavel()
    {
        // Constructor
    }

    public AStringVariavel(
        @SuppressWarnings("hiding") TCaractereVetor _caractereVetor_)
    {
        // Constructor
        setCaractereVetor(_caractereVetor_);

    }

    @Override
    public Object clone()
    {
        return new AStringVariavel(
            cloneNode(this._caractereVetor_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAStringVariavel(this);
    }

    public TCaractereVetor getCaractereVetor()
    {
        return this._caractereVetor_;
    }

    public void setCaractereVetor(TCaractereVetor node)
    {
        if(this._caractereVetor_ != null)
        {
            this._caractereVetor_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._caractereVetor_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._caractereVetor_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._caractereVetor_ == child)
        {
            this._caractereVetor_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._caractereVetor_ == oldChild)
        {
            setCaractereVetor((TCaractereVetor) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
