/* This file was generated by SableCC (http://www.sablecc.org/). */

package cordel.node;

import cordel.analysis.*;

@SuppressWarnings("nls")
public final class TBlocoInicio extends Token
{
    public TBlocoInicio()
    {
        super.setText("inicio");
    }

    public TBlocoInicio(int line, int pos)
    {
        super.setText("inicio");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TBlocoInicio(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTBlocoInicio(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TBlocoInicio text.");
    }
}
