/* This file was generated by SableCC (http://www.sablecc.org/). */

package cordel.parser;

import cordel.node.*;
import cordel.analysis.*;

class TokenIndex extends AnalysisAdapter
{
    int index;

    @Override
    public void caseTCaractere(@SuppressWarnings("unused") TCaractere node)
    {
        this.index = 0;
    }

    @Override
    public void caseTCaractereVetor(@SuppressWarnings("unused") TCaractereVetor node)
    {
        this.index = 1;
    }

    @Override
    public void caseTNumeroInteiro(@SuppressWarnings("unused") TNumeroInteiro node)
    {
        this.index = 2;
    }

    @Override
    public void caseTNumeroReal(@SuppressWarnings("unused") TNumeroReal node)
    {
        this.index = 3;
    }

    @Override
    public void caseTTipoCaractere(@SuppressWarnings("unused") TTipoCaractere node)
    {
        this.index = 4;
    }

    @Override
    public void caseTTipoInteiro(@SuppressWarnings("unused") TTipoInteiro node)
    {
        this.index = 5;
    }

    @Override
    public void caseTTipoReal(@SuppressWarnings("unused") TTipoReal node)
    {
        this.index = 6;
    }

    @Override
    public void caseTTipoBool(@SuppressWarnings("unused") TTipoBool node)
    {
        this.index = 7;
    }

    @Override
    public void caseTBoolSim(@SuppressWarnings("unused") TBoolSim node)
    {
        this.index = 8;
    }

    @Override
    public void caseTBoolNao(@SuppressWarnings("unused") TBoolNao node)
    {
        this.index = 9;
    }

    @Override
    public void caseTRuma(@SuppressWarnings("unused") TRuma node)
    {
        this.index = 10;
    }

    @Override
    public void caseTDe(@SuppressWarnings("unused") TDe node)
    {
        this.index = 11;
    }

    @Override
    public void caseTBlocoInicio(@SuppressWarnings("unused") TBlocoInicio node)
    {
        this.index = 12;
    }

    @Override
    public void caseTBlocoFim(@SuppressWarnings("unused") TBlocoFim node)
    {
        this.index = 13;
    }

    @Override
    public void caseTArrodeie(@SuppressWarnings("unused") TArrodeie node)
    {
        this.index = 14;
    }

    @Override
    public void caseTEnquanto(@SuppressWarnings("unused") TEnquanto node)
    {
        this.index = 15;
    }

    @Override
    public void caseTRepita(@SuppressWarnings("unused") TRepita node)
    {
        this.index = 16;
    }

    @Override
    public void caseTSe(@SuppressWarnings("unused") TSe node)
    {
        this.index = 17;
    }

    @Override
    public void caseTSenao(@SuppressWarnings("unused") TSenao node)
    {
        this.index = 18;
    }

    @Override
    public void caseTArrume(@SuppressWarnings("unused") TArrume node)
    {
        this.index = 19;
    }

    @Override
    public void caseTAssim(@SuppressWarnings("unused") TAssim node)
    {
        this.index = 20;
    }

    @Override
    public void caseTMande(@SuppressWarnings("unused") TMande node)
    {
        this.index = 21;
    }

    @Override
    public void caseTVolta(@SuppressWarnings("unused") TVolta node)
    {
        this.index = 22;
    }

    @Override
    public void caseTNada(@SuppressWarnings("unused") TNada node)
    {
        this.index = 23;
    }

    @Override
    public void caseTMais(@SuppressWarnings("unused") TMais node)
    {
        this.index = 24;
    }

    @Override
    public void caseTMenos(@SuppressWarnings("unused") TMenos node)
    {
        this.index = 25;
    }

    @Override
    public void caseTMultiplica(@SuppressWarnings("unused") TMultiplica node)
    {
        this.index = 26;
    }

    @Override
    public void caseTDivide(@SuppressWarnings("unused") TDivide node)
    {
        this.index = 27;
    }

    @Override
    public void caseTMaiorQue(@SuppressWarnings("unused") TMaiorQue node)
    {
        this.index = 28;
    }

    @Override
    public void caseTMenorQue(@SuppressWarnings("unused") TMenorQue node)
    {
        this.index = 29;
    }

    @Override
    public void caseTMaiorIgual(@SuppressWarnings("unused") TMaiorIgual node)
    {
        this.index = 30;
    }

    @Override
    public void caseTMenorIgual(@SuppressWarnings("unused") TMenorIgual node)
    {
        this.index = 31;
    }

    @Override
    public void caseTIgual(@SuppressWarnings("unused") TIgual node)
    {
        this.index = 32;
    }

    @Override
    public void caseTNaoOp(@SuppressWarnings("unused") TNaoOp node)
    {
        this.index = 33;
    }

    @Override
    public void caseTE(@SuppressWarnings("unused") TE node)
    {
        this.index = 34;
    }

    @Override
    public void caseTOu(@SuppressWarnings("unused") TOu node)
    {
        this.index = 35;
    }

    @Override
    public void caseTECol(@SuppressWarnings("unused") TECol node)
    {
        this.index = 36;
    }

    @Override
    public void caseTDCol(@SuppressWarnings("unused") TDCol node)
    {
        this.index = 37;
    }

    @Override
    public void caseTEPar(@SuppressWarnings("unused") TEPar node)
    {
        this.index = 38;
    }

    @Override
    public void caseTDPar(@SuppressWarnings("unused") TDPar node)
    {
        this.index = 39;
    }

    @Override
    public void caseTEChv(@SuppressWarnings("unused") TEChv node)
    {
        this.index = 40;
    }

    @Override
    public void caseTDChv(@SuppressWarnings("unused") TDChv node)
    {
        this.index = 41;
    }

    @Override
    public void caseTVirgula(@SuppressWarnings("unused") TVirgula node)
    {
        this.index = 42;
    }

    @Override
    public void caseTDoisPontos(@SuppressWarnings("unused") TDoisPontos node)
    {
        this.index = 43;
    }

    @Override
    public void caseTPontoVirgula(@SuppressWarnings("unused") TPontoVirgula node)
    {
        this.index = 44;
    }

    @Override
    public void caseTRecebe(@SuppressWarnings("unused") TRecebe node)
    {
        this.index = 45;
    }

    @Override
    public void caseTEParametro(@SuppressWarnings("unused") TEParametro node)
    {
        this.index = 46;
    }

    @Override
    public void caseTId(@SuppressWarnings("unused") TId node)
    {
        this.index = 47;
    }

    @Override
    public void caseEOF(@SuppressWarnings("unused") EOF node)
    {
        this.index = 48;
    }
}
